---
- hosts: kimai
  vars:
    ansible_python_interpreter: /usr/bin/python3

  # see https://www.kimai.org/documentation/updates.html
  tasks:

  - name: update git to new release
    become: yes
    become_user: "{{pac}}-{{user}}"
    git:
      repo: https://github.com/kevinpapst/kimai2.git
      dest: /home/pacs/{{pac}}/users/{{user}}/kimai
      version: "{{kimai_version}}"
      update: yes
      force: no

  - name: Update with composer
    become: yes
    become_user: "{{pac}}-{{user}}"
    shell: |
      ~/composer/composer.phar --no-interaction install --no-dev --optimize-autoloader -n || exit -1
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/kimai"

  - name: Upgrade Kimai
    become: yes
    become_user: "{{pac}}-{{user}}"
    shell: |
      bin/console kimai:update
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/kimai"

  # also check: https://github.com/kevinpapst/kimai2/blob/master/UPGRADING.md